const github='https://github.com/Akashkumarsenthil/';
const projects=[
{title:'ClickStream Analytics',repo:'ClickStream-analytics',category:'Data Engineering',description:'An ecommerce lakehouse connecting clickstream data, product recommendations, and analytics.',tags:['Spark','AWS S3','Iceberg / Delta / Hudi'],label:'THE DATA PLATFORM',flow:['Ingest','Lakehouse','Recommend'],footer:'Event data · Lakehouse formats · ML serving',details:['Historical clickstream processing across Bronze and lakehouse layers.','Recommendation, CTR prediction, and customer-segmentation components.','FastAPI serving and a Streamlit analytics dashboard.'],note:'Team project · DATA 228, SJSU. Includes batch processing and simulated real-time analytics. See the repository for implementation details.'},
{title:'Clinical RAG Platform',repo:'clinical-rag-platform',category:'AI / ML',description:'Document intelligence with hybrid retrieval, reranking, and a focused document workspace.',tags:['FastAPI','Qdrant','LangGraph'],label:'THE AI APPLICATION',flow:['Documents','Retrieve','Answer'],footer:'Hybrid search · Reranking · Source passages',visual:'rag',details:['Document ingestion with metadata extraction and embeddings.','Dense and BM25 retrieval combined with reciprocal-rank fusion.','Document-scoped workspace, source passages, and query monitoring.'],note:'Public demonstrations use synthetic patient data. A document-retrieval project, not a validated clinical decision-support system.'},
{title:'SafeSpan',repo:'SafeSpan-Bridge-Analytics',category:'AI / ML',description:'Bridge-condition modeling with temporal evaluation, drift analysis, and inspection prioritization.',tags:['LightGBM','Python','Explainable ML'],label:'THE ML CASE STUDY',flow:['Inspections','Model','Prioritize'],footer:'Temporal holdout · Class imbalance · Drift',visual:'ml',details:['Historical National Bridge Inventory observations and condition classification.','Model comparisons and evaluation on a later-year holdout.','Drift analysis, model explanations, and traffic-weighted inspection rankings.'],note:'Academic research project. Model results and tradeoffs are documented in the repository; rankings are not engineering safety determinations.'},
{title:'Earthquake Analytics',repo:'earthquake-analytics',demo:'https://akashkumarsenthil.github.io/earthquake-analytics/',category:'Data Engineering',description:'USGS earthquake ingestion, warehouse transformations, and an interactive analytics dashboard.'},
{title:'DataGridle',repo:'DataGridle',category:'Applications',description:'A data-interview practice platform with question workflows, SQL practice, and progress tracking.'},
{title:'Tamil Character Recognition',repo:'Tamil_OCR_',category:'AI / ML',description:'A convolutional neural network exploring printed Tamil character recognition.'},
{title:'Accident Severity Prediction',repo:'accident-severity-prediction',category:'AI / ML',description:'Classification experiments, model comparisons, and a Streamlit prediction interface.'},
{title:'Restaurant Discovery & AI Assistant',repo:'yelp-clone',category:'Applications',description:'A team-built restaurant platform with search, reviews, and an AI assistant.'},
{title:'RAG Chunking Experiments',repo:'LlamaIndex-Chunking-Techniques',category:'Labs',description:'Exploring token, semantic, and sentence-window chunking with LlamaIndex.'},
{title:'Stock Analytics with dbt',repo:'dbt-two-stock',category:'Labs',description:'A data-transformation lab exploring a dbt workflow for stock data.'},
{title:'Distributed Systems',repo:'DATA236',category:'Labs',description:'Coursework and engineering exercises from distributed systems.'},
{title:'Tempo Day Planner',repo:'tempo-day-planner',category:'Applications',description:'An AI-assisted day planner exploring natural-language task input.'},
{title:'SmartApply',repo:'SmartApply',category:'Applications',description:'An application project exploring job-search workflows.'},
{title:'DayFair',repo:'Day-Fair',category:'Applications',description:'A student platform designed to connect learning opportunities across engineering classes.'}
];
const featured=document.querySelector('#featured');
projects.slice(0,3).forEach((p,i)=>{const card=document.createElement('article');card.className='feature-card';card.innerHTML=`<div class="project-visual ${p.visual||''}"><span class="visual-label">${p.label}</span><div class="mini-flow" aria-label="Project workflow">${p.flow.map((x,j)=>`${j?'<i aria-hidden="true">→</i>':''}<span>${x}</span>`).join('')}</div><span class="visual-footer">${p.footer}</span></div><div class="feature-body"><span class="category">${p.category}</span><h3>${p.title}</h3><p>${p.description}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="card-links"><button data-project="${i}" aria-label="Explore ${p.title}">Explore project <span aria-hidden="true">↗</span></button><a href="${github+p.repo}" target="_blank" rel="noopener noreferrer" aria-label="${p.title} on GitHub">GitHub ↗</a></div></div>`;featured.append(card)});
function renderProjects(category='All'){const list=document.querySelector('#project-list');list.replaceChildren();projects.forEach((p,i)=>{if(category!=='All'&&p.category!==category)return;const link=document.createElement('a');link.className='project-row';link.href=p.demo||github+p.repo;link.target='_blank';link.rel='noopener noreferrer';link.setAttribute('aria-label',`${p.title} — ${p.demo?'open working demo':'view GitHub repository'}`);link.innerHTML=`<span class="row-num">${String(i+1).padStart(2,'0')}</span><div><span class="row-title">${p.title}</span><p class="row-desc">${p.description}</p></div><span class="row-category">${p.category}</span><span class="row-arrow" aria-hidden="true">↗</span>`;list.append(link)});document.querySelector('#project-count').textContent=`${list.children.length} projects shown`}
renderProjects();document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});renderProjects(button.dataset.filter)}));
const dialog=document.querySelector('#project-dialog');let opener;
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const p=projects[Number(button.dataset.project)];opener=button;document.querySelector('#dialog-category').textContent=p.category;document.querySelector('#dialog-title').textContent=p.title;document.querySelector('#dialog-description').textContent=p.description;document.querySelector('#dialog-details').replaceChildren(...p.details.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));document.querySelector('#dialog-note').textContent=p.note;document.querySelector('#dialog-github').href=github+p.repo;dialog.showModal()}));
document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>opener?.focus());document.querySelector('#year').textContent=new Date().getFullYear();
